trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  feedName: 'Test-feed'
  packageName: 'flask-app'
  packageVersion: '1.0.$(Build.BuildID'


strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
#Use Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip --upgrade build
      python install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo "Pipeline workspace: $(Pipeline.Workspace)"
      echo "Sources dir: $(Build.SourcesDirectory)"
      echo "Artifact staging dir: $(Build.ArtifactStagingDirectory)"
      echo "Contents of sources dir:"
      ls -la $(Build.SourcesDirectory)
      echo "Contents of artifact staging dir:"
      ls -la $(Build.ArtifactStagingDirectory)
    displayName: 'Debug paths'