trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip --upgrade build
      python -m build
    displayName: 'Build Package'

  - task: 
    displayName: 'TwineAuthenticate@1@1'
    inputs:
      artifactFeed: 'Test-feed'

  - script: |
      pythin -m pip install twine
      twine upload -r Test-feed --config-file $(PYPIRC_PATH) dist/*
    displayName: 'Upload package to Test feed'
